In [1]:
import numpy as np
import scipy as scp
import deap as dp

In [3]:
w = np.array([54,3,5,2,56,3,6,3,6,7])
w

array([54, 3, 5, 2, 56, 3, 6, 3, 6, 7])

# Podstawy pakietu NUMPY

To jest pierwszy **notebook** oparty na mechaniźmie <span style="color:red;font-size:16pt">Jupyter Notebook</span><br>
<img src="supernova.jpg" width=450>

In [4]:
def python_list_to_numpy_vector(py_list):
    return np.array(py_list)

# Testing the function with a sample list
sample_list = [1, 2, 3, 4, 5]
print(python_list_to_numpy_vector(sample_list))

[1 2 3 4 5]


In [5]:
n = np.arange(12)
n

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [6]:
w = np.array([[1,2,3,4],[6,8,10,12],[23,24,67,88]])
w

array([[ 1, 2, 3, 4],
 [ 6, 8, 10, 12],
 [23, 24, 67, 88]])

In [7]:
pylist = [[2,3,5],[7,3,6],[64,6,35]]

In [9]:
pylist[1][0]

7

In [10]:
w[1][0]

6

In [11]:
w[1,0]

6

In [13]:
# pylist[0,1]

In [14]:
nplist = np.array(pylist)

In [15]:
nplist[0,1]

3