In [1]:
import numpy as np
import scipy as scp
import deap as dp

In [3]:
w = np.array([54,3,5,2,56,3,6,3,6,7])
w

array([54, 3, 5, 2, 56, 3, 6, 3, 6, 7])

# Podstawy pakietu NUMPY

To jest pierwszy **notebook** oparty na mechaniźmie <span style="color:red;font-size:16pt">Jupyter Notebook</span><br>
<img src="supernova.jpg" width=450>

In [4]:
def python_list_to_numpy_vector(py_list):
    return np.array(py_list)

# Testing the function with a sample list
sample_list = [1, 2, 3, 4, 5]
print(python_list_to_numpy_vector(sample_list))

[1 2 3 4 5]


In [5]:
n = np.arange(12)
n

array([ 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11])

In [6]:
w = np.array([[1,2,3,4],[6,8,10,12],[23,24,67,88]])
w

array([[ 1, 2, 3, 4],
 [ 6, 8, 10, 12],
 [23, 24, 67, 88]])

In [7]:
pylist = [[2,3,5],[7,3,6],[64,6,35]]

In [9]:
pylist[1][0]

7

In [10]:
w[1][0]

6

In [11]:
w[1,0]

6

In [13]:
# pylist[0,1]

In [14]:
nplist = np.array(pylist)

In [15]:
nplist[0,1]

3

In [16]:
w = np.array([[1,2,3,4],[5,6,7,8],[14,56,78,99]])

In [17]:
w[w>5]

array([ 6, 7, 8, 14, 56, 78, 99])

In [18]:
pc = (w<5)
w[pc]

array([1, 2, 3, 4])

In [19]:
lg = (w%2==0)
w[lg]

array([ 2, 4, 6, 8, 14, 56, 78])

In [20]:
cv = w[(w>2)&(w<35)]
cv

array([ 3, 4, 5, 6, 7, 8, 14])

In [21]:
sv = w[(w<8)|(w>32)]
sv

array([ 1, 2, 3, 4, 5, 6, 7, 56, 78, 99])

In [22]:
l1 = [4,5,7]
l2 = [442,4,67]
lw = l1+l2
lw
#konkatencja list

[4, 5, 7, 442, 4, 67]

In [25]:
n1 = np.array([5,25,73])
n2 = np.array([53,6,24,3])

# nw = n1+n2
nw = np.concatenate((n1,n2))
nw

array([ 5, 25, 73, 53, 6, 24, 3])

In [26]:
dane = np.array([1,4,6])
one = np.ones(3,dtype=int)
twc = np.array([2,2,4])

print(dane+one)

[2 5 7]


In [27]:
print(dane-one)

[0 3 5]


In [28]:
print(dane*twc)

[ 2  8 24]


In [29]:
print(dane/twc)

[0.5 2.  1.5]


In [30]:
print(dane%twc==0)

[False  True False]
